### ISSUE TITLE
subtraction overflow in `withdraw` in HegicPool.sol

### ISSUE THREAD

**Issue by shapeshed** [hegic/contracts#3]
The following test case triggers a subtraction overflow when calling `withdraw` on `HegicOptions.sol`

1. Initialize contract
2. `INITIAL_RATE` is set on initialization to `1e20`
3. Provide 100000 to the pool using `provideFrom` with hedging set to `true`
4. `share` is set within `provideFrom` using `amount.mul(INITIAL_RATE)` - 100000*100000000000000000000
5. `share` is added to `hedgedShare`
4. `tranche.share` is set to `share`
4. `hedgedBalance` is set to 100000
5. Trigger a withdrawal on the tranche with `withdraw(0)`

Within `_withdraw` this causes an overflow
```
if (t.hedged) {
    amount = t.share.mul(hedgedShare).div(hedgedBalance);
    hedgedShare = hedgedShare.sub(t.share);
    hedgedBalance = hedgedBalance.sub(amount);
}
```
The values in the example are as follows
```
(10000000000000000000000000*10000000000000000000000000)/100000
10000000000000000000000000-10000000000000000000000000
100000-1000000000000000000000000000000000000000000000
```
This final subtraction triggers an overflow as a negative number is returned
```
Error: VM Exception while processing transaction: revert SafeMath: subtraction overflow
```
There is a failing test for this [here][1]

[1]: https://github.com/shapeshed/contracts/blob/7c8006b5830d80d7c9cb8c8a0c6fd81d1c00a1ef/test/sample-test.ts#L331-L346

**Comment by 0mllwntrmt3** [comment]
There was an issue with calculations of `amount` in the `_withdraw` method. I've fixed it in the last commit.
